### ISSUE TITLE
Self Host- Docker fails immediatly

### ISSUE THREAD

**Issue by ashravi92** [mhdzumair/MediaFusion#163]
Hi,

New to local deployment, when I kick off my docker, it fails immediately

```
dramatiq-worker-1  | Process Process-8:
2024-04-05 12:06:14 dramatiq-worker-1  | Traceback (most recent call last):
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-04-05 12:06:14 dramatiq-worker-1  |     self.run()
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-04-05 12:06:14 dramatiq-worker-1  |     self._target(*self._args, **self._kwargs)
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/dramatiq/cli.py", line 393, in worker_process
2024-04-05 12:06:14 dramatiq-worker-1  |     module, broker = import_broker(args.broker)
2024-04-05 12:06:14 dramatiq-worker-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/dramatiq/cli.py", line 123, in import_broker
2024-04-05 12:06:14 dramatiq-worker-1  |     module, broker_or_callable = import_object(value)
2024-04-05 12:06:14 dramatiq-worker-1  |                                  ^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/dramatiq/cli.py", line 112, in import_object
2024-04-05 12:06:14 dramatiq-worker-1  |     module = importlib.import_module(modname)
2024-04-05 12:06:14 dramatiq-worker-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-04-05 12:06:14 dramatiq-worker-1  |     return _bootstrap._gcd_import(name[level:], package, level)
2024-04-05 12:06:14 dramatiq-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/mediafusion/api/__init__.py", line 6, in <module>
2024-04-05 12:06:14 dramatiq-worker-1  |     from db.config import settings
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/mediafusion/db/config.py", line 41, in <module>
2024-04-05 12:06:14 dramatiq-worker-1  |     settings = Settings()
2024-04-05 12:06:14 dramatiq-worker-1  |                ^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__
2024-04-05 12:06:14 dramatiq-worker-1  |     super().__init__(
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
2024-04-05 12:06:14 dramatiq-worker-1  |     self.__pydantic_validator__.validate_python(data, self_instance=self)
2024-04-05 12:06:14 dramatiq-worker-1  | pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
2024-04-05 12:06:14 dramatiq-worker-1  | secret_key
2024-04-05 12:06:14 dramatiq-worker-1  |   Field required [type=missing, input_value={'mongo_uri': 'mongodb://...le_rate_limit': 'false'}, input_type=dict]
2024-04-05 12:06:14 dramatiq-worker-1  |     For further information visit https://errors.pydantic.dev/2.6/v/missing
2024-04-05 12:06:14 dramatiq-worker-1  | Process Process-3:
2024-04-05 12:06:14 dramatiq-worker-1  | Traceback (most recent call last):
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-04-05 12:06:14 dramatiq-worker-1  |     self.run()
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-04-05 12:06:14 dramatiq-worker-1  |     self._target(*self._args, **self._kwargs)
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/dramatiq/cli.py", line 393, in worker_process
2024-04-05 12:06:14 dramatiq-worker-1  |     module, broker = import_broker(args.broker)
2024-04-05 12:06:14 dramatiq-worker-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/dramatiq/cli.py", line 123, in import_broker
2024-04-05 12:06:14 dramatiq-worker-1  |     module, broker_or_callable = import_object(value)
2024-04-05 12:06:14 dramatiq-worker-1  |                                  ^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/dramatiq/cli.py", line 112, in import_object
2024-04-05 12:06:14 dramatiq-worker-1  |     module = importlib.import_module(modname)
2024-04-05 12:06:14 dramatiq-worker-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-04-05 12:06:14 dramatiq-worker-1  |     return _bootstrap._gcd_import(name[level:], package, level)
2024-04-05 12:06:14 dramatiq-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-04-05 12:06:14 dramatiq-worker-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/mediafusion/api/__init__.py", line 6, in <module>
2024-04-05 12:06:14 dramatiq-worker-1  |     from db.config import settings
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/mediafusion/db/config.py", line 41, in <module>
2024-04-05 12:06:14 dramatiq-worker-1  |     settings = Settings()
2024-04-05 12:06:14 dramatiq-worker-1  |                ^^^^^^^^^^
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__
2024-04-05 12:06:14 dramatiq-worker-1  |     super().__init__(
2024-04-05 12:06:14 dramatiq-worker-1  |   File "/root/.local/share/virtualenvs/mediafusion-ZmKbvzsi/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
2024-04-05 12:06:14 dramatiq-worker-1  |     self.__pydantic_validator__.validate_python(data, self_instance=self)
2024-04-05 12:06:14 dramatiq-worker-1  | pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
2024-04-05 12:06:14 dramatiq-worker-1  | secret_key
2024-04-05 12:06:14 dramatiq-worker-1  |   Field required [type=missing, input_value={'mongo_uri': 'mongodb://...le_rate_limit': 'false'}, input_type=dict]
2024-04-05 12:06:14 dramatiq-worker-1  |     For further information visit https://errors.pydantic.dev/2.6/v/missing
dramatiq-worker-1 exited with code 1
```

**Comment by mhdzumair** [comment]
@ashravi92 as you can see in the logs, it's missing the `secret_key` value. Make sure to set the secret key according to the documentation.
