### ISSUE TITLE
Crashes on Chromecast / Android TV

### ISSUE THREAD

**Issue by tinychimp** [mhdzumair/MediaFusion#18]
After the recent changes, the add on breaks on Android TV on Chromecast. It causes the app to crash when scrolling down to any Media Fusion carousel. Tried uninstalling and then reinstalling. Issue happens only with the MediaFusion add on. Was working fine previously before this change.

**Comment by mhdzumair** [comment]
@tinychimp the issue is due to new poster image urls from IMDB. Now I reverted to site image urls. Please uninstall again and reinstall from add-on config page.

**Comment by tinychimp** [comment]
No luck. I tried reinstalling, but it still crashes. 

Also, cannot get past the RD authorization page anymore. The add on freezes stremio as soon as you click "Authorize realdebrid". You cannot scroll down to install / apply the change.

**Comment by mhdzumair** [comment]
Which link are you using? What is the device used for accessing configuration page? 

Use this link https://882b9915d0fe-mediafusion.baby-beamup.club/configure

**Comment by mhdzumair** [comment]
okay i finally able to reproduce the error on emulator and got the logcat. Its crashing due to the larger poster image. ill create a bug in stremio 

```
--------- beginning of crash
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: FATAL EXCEPTION: main
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: Process: com.stremio.one, PID: 13148
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(388800000bytes) bitmap.
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:109)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1418)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22350)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.leanback.widget.ShadowOverlayContainer.draw(ShadowOverlayContainer.java:246)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5499)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5499)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4101)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8184)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-13 01:23:22.394 10079 13148 13148 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-13 01:23:22.532 10079 13148 13176 D libcrashlytics: Initializing libcrashlytics version 3.2.0
10-13 01:23:22.535 10079 13148 13176 D libcrashlytics: Initializing native crash handling successful.
10-13 01:23:19.896  1000   518  6569 I ProcessStatsService: Added stats: 2023-09-12-07-59-16, over +32m4s399ms
10-13 01:23:22.616  1000   518 15040 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-13 01:23:22.618  1000   518  6293 W ActivityTaskManager:   Force finishing activity com.stremio.one/com.stremio.tv.MainActivity
10-13 01:23:22.631  1000   298   421 D goldfish-address-space: claimShared: Ask to claim region [0x3f4000000 0x3f47e9000]
10-13 01:23:22.645  1000   518  7116 D HostConnection: HostConnection::get() New Host Connection established 0xb588e240, tid 7116
10-13 01:23:22.646 10079 13148 13148 I Process : Sending signal. PID: 13148 SIG: 9
10-13 01:23:22.649  1000   518  7116 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
10-13 01:23:22.653  1000   518   543 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-13 01:23:22.653  1000   518   543 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-13 01:23:22.655  1000   518  7116 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
10-13 01:23:22.656  1000   518  7116 D EGL_emulation: eglCreateContext: 0xb588feb0: maj 3 min 0 rcv 3
10-13 01:23:22.657  1000   518  7116 D EGL_emulation: eglMakeCurrent: 0xb588feb0: ver 3 0 (tinfo 0xc1d84b70) (first time)
10-13 01:23:22.763  1000   518   595 W InputDispatcher: Waiting because no window has focus but ActivityRecord{29f44e0 u0 com.google.android.apps.tv.launcherx/.home.HomeActivity t16} may eventually add a window when it finishes starting up. Will wait for 5000ms
10-13 01:23:22.763  1000   518   595 W InputDispatcher: Still no focused window. Will drop the event in 4999ms
10-13 01:23:22.779  1000   518   595 W InputDispatcher: Still no focused window. Will drop the event in 4983ms
10-13 01:23:22.781  1000   518  3627 I WindowManager: WIN DEATH: Window{906437a u0 com.stremio.one/com.stremio.tv.MainActivity}
10-13 01:23:22.781  1000   518  3627 W InputDispatcher: Attempted to unregister already unregistered input channel '906437a com.stremio.one/com.stremio.tv.MainActivity (server)'
10-13 01:23:22.781  1000   518  5184 I ActivityManager: Process com.stremio.one (pid 13148) has died: prcp TOP 
10-13 01:23:22.782  root   282   282 I Zygote  : Process 13148 exited due to signal 9 (Killed)
10-13 01:23:22.784  1000   518   545 I libprocessgroup: Successfully killed process cgroup uid 10079 pid 13148 in 2ms
```

**Comment by mhdzumair** [comment]
I have created the detailed issue in stremio bugs repo. https://github.com/Stremio/stremio-bugs/issues/575

Please give thumbs up or your comments on there to prioritize the issue.
